const { get, all, run, exec } = require('./db');

function seed() {
  const count = get('SELECT COUNT(*) as c FROM users');
  if (count && count.c > 0) {
    exec('DELETE FROM risks_opportunities; DELETE FROM reports; DELETE FROM market_entry_strategies; DELETE FROM swot_analysis; DELETE FROM competitor_pricing; DELETE FROM competitors; DELETE FROM markets; DELETE FROM users; DELETE FROM change_history; DELETE FROM notifications;');
  }

  run(`INSERT INTO users (user_id, username, email, password_hash, role, created_at) VALUES (1, 'admin', 'admin@cas.io', 'admin123', 'admin', '2026-01-15T08:00:00Z')`);
  run(`INSERT INTO users (user_id, username, email, password_hash, role, created_at) VALUES (2, 'analyst', 'analyst@cas.io', 'analyst123', 'analyst', '2026-01-15T08:00:00Z')`);
  run(`INSERT INTO users (user_id, username, email, password_hash, role, created_at) VALUES (3, 'viewer', 'viewer@cas.io', 'viewer123', 'viewer', '2026-01-15T08:00:00Z')`);

  run(`INSERT INTO markets (market_id, market_name, country, industry, market_size_usd, growth_rate, target_segment, created_by, created_at) VALUES (1, 'China - Skincare', 'China', 'FMCG', 52000000000, 8.5, 'Urban Youth 18-30', 2, '2026-02-01T10:00:00Z')`);
  run(`INSERT INTO markets (market_id, market_name, country, industry, market_size_usd, growth_rate, target_segment, created_by, created_at) VALUES (2, 'Southeast Asia - Electronics', 'Vietnam', 'Consumer Electronics', 18000000000, 12.3, 'Middle-class consumers 25-45', 2, '2026-02-10T10:00:00Z')`);

  run(`INSERT INTO competitors (competitor_id, market_id, company_name, country_origin, founded_year, revenue_usd, market_share, website, description, added_by, created_at) VALUES (1, 1, 'PerfectDiary (逸仙电商)', 'China', 2017, 780000000, 6.2, 'https://www.perfectdiary.com', 'Leading Chinese DTC beauty brand known for affordable luxury cosmetics with strong social media presence.', 2, '2026-02-05T10:00:00Z')`);
  run(`INSERT INTO competitors (competitor_id, market_id, company_name, country_origin, founded_year, revenue_usd, market_share, website, description, added_by, created_at) VALUES (2, 1, 'Florasis (花西子)', 'China', 2017, 450000000, 4.1, 'https://www.florasis.com', 'Premium Chinese beauty brand inspired by traditional Chinese aesthetics and herbal ingredients.', 2, '2026-02-05T10:00:00Z')`);
  run(`INSERT INTO competitors (competitor_id, market_id, company_name, country_origin, founded_year, revenue_usd, market_share, website, description, added_by, created_at) VALUES (3, 1, 'Proya Cosmetics', 'China', 2003, 920000000, 5.8, 'https://www.proya.com', 'Established Chinese skincare company with diversified product portfolio spanning multiple price points.', 2, '2026-02-06T10:00:00Z')`);
  run(`INSERT INTO competitors (competitor_id, market_id, company_name, country_origin, founded_year, revenue_usd, market_share, website, description, added_by, created_at) VALUES (4, 2, 'VinSmart', 'Vietnam', 2018, 320000000, 8.5, 'https://www.vinsmart.vn', 'Vietnamese technology company producing smartphones and smart home devices for the domestic market.', 2, '2026-02-12T10:00:00Z')`);

  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (1, 1, 'Explorer Eyeshadow Palette', 15.99, 'budget', 'Regular flash sales on Tmall, bundle deals', 'Online (Tmall, JD) + Offline (pop-up stores)', 'Strong KOL marketing drives volume')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (2, 1, 'Moisturizing Lip Glaze', 8.50, 'budget', 'Buy 2 get 1 free promotions', 'Online primarily', 'Best-selling SKU')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (3, 2, 'Phoenix Carved Lipstick', 28.00, 'premium', 'Limited edition collections, minimal discounting', 'Online (own site, Tmall) + Select retail', 'Iconic product with cultural design elements')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (4, 2, 'Jade Pressed Powder', 35.00, 'premium', 'Gift sets during festivals', 'Online + Department stores', 'Traditional Chinese medicine ingredients')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (5, 3, 'Dual-Action Serum', 22.00, 'mid-range', 'Seasonal promotions, membership discounts', 'Online + 3000+ offline counters', 'Top-selling serum in China 2025')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (6, 3, 'Anti-aging Night Cream', 38.00, 'mid-range', '20% off annual membership', 'Full omnichannel', 'Competing directly with international brands')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (7, 4, 'VinSmart Live 4', 129.00, 'budget', 'Carrier bundle deals, trade-in programs', 'Offline retail + Online (Shopee, Lazada)', 'Entry-level smartphone for mass market')`);
  run(`INSERT INTO competitor_pricing (pricing_id, competitor_id, product_name, price_usd, pricing_model, discount_policy, distribution, notes) VALUES (8, 4, 'VinSmart Joy 5+', 199.00, 'mid-range', 'Holiday promotions', 'Vincom malls + Online', 'Competing with Samsung Galaxy A series')`);

  run(`INSERT INTO swot_analysis (swot_id, competitor_id, strengths, weaknesses, opportunities, threats, analyzed_by, analyzed_at) VALUES (1, 1, 'Strong DTC model with massive social media following\nAggressive pricing strategy captures volume\nData-driven product development\nRapid product launch cycles (monthly releases)', 'Low brand loyalty due to budget positioning\nLimited international presence\nHeavy reliance on influencer marketing spend\nThin profit margins', 'International expansion to SE Asia and Japan\nMove upmarket with premium sub-brands\nMen''s grooming category entry\nLivestream commerce growth', 'Intense domestic competition from 100+ local brands\nInternational luxury brands going affordable\nRising marketing costs on Chinese social platforms\nRegulatory changes in cosmetics testing', 2, '2026-03-01T10:00:00Z')`);
  run(`INSERT INTO swot_analysis (swot_id, competitor_id, strengths, weaknesses, opportunities, threats, analyzed_by, analyzed_at) VALUES (2, 2, 'Unique cultural positioning differentiates from competitors\nPremium pricing with strong margins\nLimited editions create scarcity and buzz\nBeautiful packaging design as collectibles', 'Narrow product range focused on makeup\nSlow expansion pace compared to peers\nHigh production costs for intricate designs\nLimited skincare expertise', 'Cultural wave (国潮) trend boosting domestic brands\nExpansion into skincare segment\nGlobal interest in Chinese beauty traditions\nCollaboration with cultural institutions', 'Cultural trend fatigue among younger consumers\nCopycat brands diluting uniqueness\nRising material costs for specialty packaging\nEconomic slowdown affecting premium spending', 2, '2026-03-01T10:00:00Z')`);
  run(`INSERT INTO swot_analysis (swot_id, competitor_id, strengths, weaknesses, opportunities, threats, analyzed_by, analyzed_at) VALUES (3, 3, 'Established brand with 20+ years in market\nDiversified product portfolio across price points\nExtensive offline retail network\nStrong R&D capabilities with own labs', 'Brand perceived as "older generation"\nSlower digital transformation\nMultiple sub-brands cause market confusion\nLess social media savviness vs newer brands', 'Digital transformation and DTC channel development\nPremium positioning upgrade\nMale grooming market expansion\nMerger and acquisition of indie brands', 'Rapid rise of new DTC competitors\nInternational brands with localized strategies\nPrice wars eroding margins\nChanging consumer preferences toward niche brands', 2, '2026-03-02T10:00:00Z')`);
  run(`INSERT INTO swot_analysis (swot_id, competitor_id, strengths, weaknesses, opportunities, threats, analyzed_by, analyzed_at) VALUES (4, 4, 'Strong parent company (Vingroup) backing\nLocal brand patriotism advantage\nCompetitive pricing in budget segment\nGrowing R&D investment', 'Limited brand recognition outside Vietnam\nSmall product lineup vs Samsung/Apple\nDependency on parent company resources\nLimited software ecosystem', 'Vietnamese smartphone market growing 15% YoY\nGovernment support for domestic tech brands\n5G adoption creating upgrade cycle\nSmart home ecosystem development', 'Dominance of Chinese brands (Xiaomi, Oppo)\nSamsung''s aggressive mid-range pricing\nGlobal chip shortage affecting production\nConsumer preference for established brands', 2, '2026-03-05T10:00:00Z')`);

  run(`INSERT INTO market_entry_strategies (strategy_id, market_id, strategy_title, entry_mode, target_segment, estimated_cost, timeline_months, key_risks, expected_roi, created_by, created_at) VALUES (1, 1, 'India-to-China Skincare Entry via Joint Venture', 'joint venture', 'Urban Youth 18-30', 5000000, 18, 'Regulatory approval delays for cosmetics imports\nComplex IP protection landscape\nCultural differences in beauty standards\nNeed for local partner due diligence', 22.5, 2, '2026-03-10T10:00:00Z')`);
  run(`INSERT INTO market_entry_strategies (strategy_id, market_id, strategy_title, entry_mode, target_segment, estimated_cost, timeline_months, key_risks, expected_roi, created_by, created_at) VALUES (2, 2, 'Direct Export to Vietnam Electronics Market', 'direct export', 'Middle-class consumers 25-45', 2000000, 12, 'High tariff barriers on electronics imports\nEntrenched competition from Samsung and Chinese brands\nDistribution network establishment\nAfter-sales service infrastructure needed', 15.0, 2, '2026-03-12T10:00:00Z')`);

  run(`INSERT INTO reports (report_id, market_id, strategy_id, report_title, summary, version, status, created_by, created_at) VALUES (1, 1, 1, 'China Skincare Market Entry Assessment Q1 2026', 'Comprehensive analysis of the Chinese skincare market opportunity for Indian brand entry. The $52B market shows strong growth at 8.5% CAGR. Key competitors include Perfect Diary, Florasis, and Proya. Recommended entry via joint venture with estimated $5M investment and 22.5% ROI within 18 months. Major risks include regulatory complexity and intense domestic competition.', 1, 'final', 2, '2026-03-15T10:00:00Z')`);
  run(`INSERT INTO reports (report_id, market_id, strategy_id, report_title, summary, version, status, created_by, created_at) VALUES (2, 2, 2, 'Vietnam Electronics Market Preliminary Report', 'Initial assessment of the Vietnamese consumer electronics market for direct export strategy. Market valued at $18B with 12.3% growth. VinSmart identified as key local competitor. Direct export route recommended with $2M initial investment. Further analysis needed on distribution partnerships and regulatory requirements.', 1, 'draft', 2, '2026-03-18T10:00:00Z')`);

  run(`INSERT INTO risks_opportunities (tag_id, market_id, competitor_id, type, title, description, severity, tagged_by, created_at) VALUES (1, 1, 1, 'risk', 'Price War Escalation', 'Perfect Diary may further reduce prices to defend market share against new entrants, potentially triggering an unsustainable price war.', 'high', 2, '2026-03-01T10:00:00Z')`);
  run(`INSERT INTO risks_opportunities (tag_id, market_id, competitor_id, type, title, description, severity, tagged_by, created_at) VALUES (2, 1, NULL, 'risk', 'Regulatory Compliance Delays', 'Chinese cosmetics regulation requires animal testing exemption certificates and NMPA registration, which can take 6-12 months.', 'high', 2, '2026-03-02T10:00:00Z')`);
  run(`INSERT INTO risks_opportunities (tag_id, market_id, competitor_id, type, title, description, severity, tagged_by, created_at) VALUES (3, 1, NULL, 'opportunity', 'Ayurvedic Ingredient Differentiation', 'Indian ayurvedic and herbal ingredients are gaining popularity in China. Positioning around natural/traditional ingredients could differentiate from local competitors.', 'high', 2, '2026-03-03T10:00:00Z')`);
  run(`INSERT INTO risks_opportunities (tag_id, market_id, competitor_id, type, title, description, severity, tagged_by, created_at) VALUES (4, 1, 2, 'opportunity', 'Florasis Segment Gap', 'Florasis focuses primarily on makeup with limited skincare offering. This creates an opportunity to capture skincare consumers seeking cultural/traditional positioning.', 'medium', 2, '2026-03-04T10:00:00Z')`);
  run(`INSERT INTO risks_opportunities (tag_id, market_id, competitor_id, type, title, description, severity, tagged_by, created_at) VALUES (5, 2, 4, 'risk', 'VinSmart Government Backing', 'VinSmart benefits from strong government support for domestic manufacturing, creating potential regulatory advantages over foreign competitors.', 'medium', 2, '2026-03-05T10:00:00Z')`);
  run(`INSERT INTO risks_opportunities (tag_id, market_id, competitor_id, type, title, description, severity, tagged_by, created_at) VALUES (6, 2, NULL, 'opportunity', 'E-commerce Infrastructure Growth', 'Vietnam''s e-commerce market growing at 25% YoY with Shopee and Lazada penetration increasing. Direct-to-consumer channel viable without heavy retail investment.', 'high', 2, '2026-03-06T10:00:00Z')`);

  console.log('Database seeded with demo data');
}

module.exports = { seed };
